import { CardFieldType } from "../../interfaces/CardFieldType";

export const cardFieldTypeList: CardFieldType[] = [
  {
    fieldType: "单行文本",
    dataType: "string",
    fieldIcon: "https://z3.ax1x.com/2021/09/13/4Caom4.png",
    fieldName: "",
    meaning: "",
  },
  {
    fieldType: "多行文本",
    dataType: "string",
    fieldIcon: "https://z3.ax1x.com/2021/09/13/4CdUHJ.png",
    fieldName: "",
    meaning: "",
  },
  {
    fieldType: "开关",
    dataType: "boolean",
    fieldIcon: "https://z3.ax1x.com/2021/09/13/4Cy5dO.png",
    fieldName: "",
    meaning: "",
  },
  {
    fieldType: "货币",
    dataType: "number",
    fieldIcon: "https://z3.ax1x.com/2021/09/13/4CdtuF.png",
    fieldName: "",
    meaning: "",
    symbol: "",
    alignment: "left",
    precision: 2,
  },
  {
    fieldType: "百分比",
    dataType: "number",
    fieldIcon: "https://z3.ax1x.com/2021/09/13/4Cd83V.png",
    fieldName: "",
    meaning: "",
    precision: 1,
  },
  {
    fieldType: "协作成员",
    dataType: "array",
    fieldIcon: "https://z3.ax1x.com/2021/09/13/4Cd390.png",
    fieldName: "",
    meaning: "",
    limitNum: 1,
  },
  {
    fieldType: "单选",
    dataType: "string",
    fieldIcon: "https://z3.ax1x.com/2021/09/13/4CyIoD.png",
    fieldName: "",
    meaning: "",
    optionArr: [],
  },
  {
    fieldType: "多选",
    dataType: "array",
    fieldIcon: "https://z3.ax1x.com/2021/09/13/4Cy7JH.png",
    fieldName: "",
    meaning: "",
    optionArr: [],
  },
  {
    fieldType: "附件",
    dataType: "string",
    fieldIcon: "https://z3.ax1x.com/2021/09/13/4CdQNn.png",
    fieldName: "",
    meaning: "",
    limitNum: 1,
  },
  {
    fieldType: "评分",
    dataType: "number",
    fieldIcon: "https://z3.ax1x.com/2021/09/13/4CdMAs.png",
    fieldName: "",
    meaning: "",
    subIcon: "",
    maxScore: 5,
  },
  {
    fieldType: "日期",
    dataType: "string",
    fieldIcon: "https://z3.ax1x.com/2021/09/13/4CdA9P.png",
    fieldName: "",
    meaning: "",
  },
  {
    fieldType: "数字",
    dataType: "number",
    fieldIcon: "https://z3.ax1x.com/2021/09/13/4Cdu7j.png",
    fieldName: "",
    meaning: "",
    unit: "",
    thousandthShow: true,
    precision: 1,
  },
  {
    fieldType: "链接",
    dataType: "string",
    fieldIcon: "https://z3.ax1x.com/2021/09/13/4CdZjS.png",
    fieldName: "",
    meaning: "",
  },
  {
    fieldType: "姓名",
    dataType: "string",
    fieldIcon: "https://z3.ax1x.com/2021/09/13/4CdE1f.png",
    fieldName: "",
    meaning: "",
  },
  {
    fieldType: "电话",
    dataType: "string",
    fieldIcon: "https://z3.ax1x.com/2021/09/13/4CdVc8.png",
    fieldName: "",
    meaning: "",
  },
  {
    fieldType: "邮箱",
    dataType: "string",
    fieldIcon: "https://z3.ax1x.com/2021/09/13/4Cdmng.png",
    fieldName: "",
    meaning: "",
  },
  {
    fieldType: "地址",
    dataType: "string",
    fieldIcon: "https://z3.ax1x.com/2021/09/13/4CyTFe.png",
    fieldName: "",
    meaning: "",
  },
  {
    fieldType: "身份证",
    dataType: "string",
    fieldIcon: "https://z3.ax1x.com/2021/09/13/4Cy4eK.png",
    fieldName: "",
    meaning: "",
  },
];
